# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'ls -la',
  'npm ci',
  'ls -la server',
  '(cd server && npm ci)'
]

[phases.build]
cmds = [
  '(cd server && npm run build)'
]

[start]
cmd = 'cd server && npm start'